#!/bin/bash

RED='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m'

x=''

cd simulator
make
if [ $? != 0 ]; then
    exit 1
fi

cd ..

for a in `cat list`
do
    echo ">>> Testcase $a ......"
    cp testcase/$a/dimage.bin .
    cp testcase/$a/iimage.bin .
    cp simulator/pipeline .
    ./pipeline

    diff snapshot.rpt testcase/$a/snapshot.rpt
    if [ $? != 0 ]; then
        echo "some difference in snapshot.rpt!"
        echo "Press enter to see more details"
        read x
        vimdiff snapshot.rpt testcase/$a/snapshot.rpt
        exit 1
    fi

    diff error_dump.rpt testcase/$a/error_dump.rpt
    if [ $? != 0 ]; then
        echo "some difference in error_dump.rpt!"
        echo "Press enter to see more details"
        read x
        vimdiff error_dump.rpt testcase/$a/error_dump.rpt
        exit 1
    fi
    echo -e "......................${GREEN}PASS!${NC}"
done

